In [ ]:
 #.  CS 549 NATURAL LANGUAGE PROCESSING PAPER : EXPLOARITONS ON MEANING MAP METHODS

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re


In [3]:
data = pd.read_csv('OPTED-Dictionary.csv')

In [40]:
#Creation of the algorithm
def create_sözlük(sub_data):
    sözlük = {}
    liste_kelimeler=list(sub_data["Word"].unique())
    for i in range(len(liste_kelimeler)):
        sözlük[liste_kelimeler[i].lower()] = i
    return sözlük


def definitions_to_sözlük(sözlük,sub_data):
    liste_kelimeler=list(sub_data["Word"].unique())
    for i in liste_kelimeler:
        definitions = sub_data[sub_data["Word"] == i]
        for k in range(definitions.shape[0]):
            old_string = definitions["Definition"].iloc[k]
            new_string = re.sub(r'[^\w\s]', '', old_string)
            new_string = new_string.lower()
            new_string_list = new_string.split(" ")
            for p in new_string_list:
                if p in sözlük.keys():
                    pass
                else:
                    sözlük[p] = max(sözlük.values())+1
    return sözlük

def initialize_meaning_map(sözlük):
    meaning_map = np.zeros((len(sözlük.keys()),len(sözlük.keys())))
    return meaning_map




def meaning_map_assigner(word,string_list,meaning_map,sözlük):
    
    for i in string_list:
        for k in string_list:
            if i == k:
                pass
            else:
                if sözlük[k] >= meaning_map.shape[0] or sözlük[i] >= meaning_map.shape[0] :
                    print(sözlük[k])
                    continue
                else:    
                    meaning_map[sözlük[i],sözlük[k]] += 1
                    meaning_map[sözlük[k],sözlük[i]] += 1
                
    for i in string_list:
        if sözlük[k] >= meaning_map.shape[0] or sözlük[i] >= meaning_map.shape[0] :
                    print(sözlük[k])
                    continue
        else:
            meaning_map[sözlük[word],sözlük[i]] += 1
            meaning_map[sözlük[i],sözlük[word]] += 1
   

        
def constructing_meaning_map(sözlük,sub_data,meaning_map):
    liste_kelimeler=list(sub_data["Word"].unique())

    for i in liste_kelimeler:
        definitions = sub_data[sub_data["Word"] == i]
        for k in range(definitions.shape[0]):
            old_string = definitions["Definition"].iloc[k]
            new_string = re.sub(r'[^\w\s]', '', old_string)
            new_string = new_string.lower()
            new_string_list = new_string.split(" ")
            meaning_map_assigner(i.lower(),new_string_list,meaning_map,sözlük)
    return meaning_map
                
def vector_extractor(word,meaning_map,sözlük):
    return meaning_map[:,sözlük[word]]  
        
def related_words(t_array,sözlük,limit = 0):
    related_words = []
    sözlük_liste = list(sözlük.keys())
    for i in range(t_array.shape[0]):
        if t_array[i] >= limit:
            related_words.append(sözlük_liste[i])
        else:
            pass
    return related_words
        
    
    
def compare_two_arrays(first_word,second_word,meaning_map):
    array_t_old = vector_extractor(first_word,meaning_map,sözlük)
    array_t_new = vector_extractor(second_word,meaning_map,sözlük)
    A = array_t_old
    B = array_t_new
    cosine = np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))
    return cosine 

def evaluation_algorithm(data_frame1,data_frame2,column_name1,column_name2):
    order_nonextract_1 = order_given_dataframe(data_frame1,column_name1)
    order_nonextract_2 = order_given_dataframe(data_frame2,column_name2)
    first_ordering,second_ordering = extract_ordering(order_nonextract_1,order_nonextract_2)
    correct,wrong,list_correct = comparison_algorithm(first_ordering,second_ordering)
    return correct,wrong,list_correct
    
    



def comparison_algorithm(first_ordering,second_ordering):
    done = 0
    correct = []
    wrong = []
    for i in range(10):
        counter1 = 0
        counter2 = 0
        if len(first_ordering) < 1 or len(second_ordering) < 1:
            return 0,0,0
        
        elif first_ordering == second_ordering:
            done == 1
            
      
        while done != 1:
            
            if first_ordering[counter1] == second_ordering[counter2]:
                correct.append(first_ordering[counter1][0])
                counter1 += 1
                counter2 += 1
                
                
            else:
                wrong.append(first_ordering[counter2][0])
                first_ordering.remove(second_ordering[counter2])
                second_ordering.remove(second_ordering[counter2])
                break
                
            if counter1 >= len(first_ordering):
                done = 1
    return len(set(correct)), len(set(wrong)),0
            
        
        
        


def extract_ordering(sorted_frame1,sorted_frame2):
    first_ordering = sorted_frame1[["word2"]].values.tolist()
    second_ordering = sorted_frame2[["word2"]].values.tolist()
    return first_ordering,second_ordering
    
    

    
    
def order_given_dataframe(dataframe,column_name):
    sorted_dataframe = dataframe.sort_values(column_name,ascending = False)
    return sorted_dataframe
    

In [ ]:
#Learning from corpus   What functions we need? We need a function that divides the corpus into sentences.
#After dividing the sentences we split each sentence into words and then we update the connections of the dictionary.
# If the word did not exist before in the dictionary we add it to the meaning map and dictionary creating a new world.


In [56]:
sub_data = data.iloc[:10000,:].copy()
sözlük = create_sözlük(sub_data)
sözlük = definitions_to_sözlük(sözlük,sub_data)
meaning_map = initialize_meaning_map(sözlük)
meaning_map = constructing_meaning_map(sözlük,sub_data,meaning_map)


18771
18771
6876
6441
18771
18771
18771


In [57]:
string_of_stop = "a, an, the, in, on, at, for, of, by, with, to, from, about, over, under, and, or, not, but, so, as, if, when, where, how, what, who, which, is, am, are, was, were, be, being, been, has, have, had, do, does, did, can, could, will, would, should, may, might, must, shall, let, there, their, they, them, it, its, we, us, our, ours, you, your, yours, I, me, my, mine, myself, yourself, himself, herself, itself, themselves, he, she, it, him, her, his, hers, they, them, these, those, this, that, each, every, some, any, all, both, few, many, much, more, most, other, another, such, no, nor, only, same, than, too, very, through, between, among, until, since, during, while, unless, except, without, off, about, above, across, after, against, along, around, as, before, behind, below, beneath, beside, between, beyond, but, concerning, considering, despite, down, during, except, following, inside, into, like, near, next, of, off, on, onto, out, outside, over, past, regarding, round, since, through, throughout, till, to, toward, under, underneath, until, unto, upon, versus, via, within, without"

liste_of_stop = string_of_stop.split(", ")
set_of_stop = set(liste_of_stop)
#print(set_of_stop)



for i in set_of_stop:
    if i in sözlük:
        print(i)
        print(meaning_map[sözlük[i],:])
        meaning_map[sözlük[i],:] = np.ones((meaning_map[sözlük[i],:].shape))
        print(i)
        print(meaning_map[sözlük[i],:])
        print("---------------------------")
        
    else:
        pass

few
[12.  0.  0. ...  0.  0.  0.]
few
[1. 1. 1. ... 1. 1. 1.]
---------------------------
except
[6. 0. 0. ... 0. 0. 0.]
except
[1. 1. 1. ... 1. 1. 1.]
---------------------------
some
[344.   0.   0. ...   0.   0.   0.]
some
[1. 1. 1. ... 1. 1. 1.]
---------------------------
there
[54.  0.  0. ...  0.  0.  0.]
there
[1. 1. 1. ... 1. 1. 1.]
---------------------------
into
[477.   0.   0. ...   0.   0.   0.]
into
[1. 1. 1. ... 1. 1. 1.]
---------------------------
do
[40.  0.  0. ...  0.  0.  0.]
do
[1. 1. 1. ... 1. 1. 1.]
---------------------------
will
[38.  0.  0. ...  0.  0.  0.]
will
[1. 1. 1. ... 1. 1. 1.]
---------------------------
itself
[61.  0.  0. ...  0.  0.  0.]
itself
[1. 1. 1. ... 1. 1. 1.]
---------------------------
she
[0. 0. 0. ... 0. 0. 0.]
she
[1. 1. 1. ... 1. 1. 1.]
---------------------------
past
[12.  0.  0. ...  0.  0.  0.]
past
[1. 1. 1. ... 1. 1. 1.]
---------------------------
within
[48.  0.  0. ...  0.  0.  0.]
within
[1. 1. 1. ... 1. 1. 1.]
----------

In [58]:
# Read the data from the text file
simlex_data = pd.read_csv("Simlex-999.txt", delimiter='\t')

# Specify the column names
column_names = ["word1", "word2", "POS", "SimLex999", "conc(w1)", "conc(w2)", "concQ", "Assoc(USF)", "SimAssoc333", "SD(SimLex)"]

# Create the DataFrame
simlex_dataframe = pd.DataFrame(simlex_data.values, columns=column_names)

# Print the resulting DataFrame
simlex_dataframe.rename(columns = {"concQ":"MM"},inplace=True)
unique_liste = list(simlex_dataframe["word1"].unique())


In [59]:
dicti = {}
for i in unique_liste:
    a = simlex_dataframe[simlex_dataframe["word1"] == i]
    #a["concQ"].iloc[0] = 10
    if i in sözlük.keys():
        for k in range(a.shape[0]):
            word1 = a.iloc[k]["word1"]
            word2 = a.iloc[k]["word2"]
            if word2 in sözlük.keys():
                cosine = compare_two_arrays(word1,word2,meaning_map)
                a["MM"].iloc[k] = cosine
                dicti[i] = a
            else:
                a["MM"].iloc[k] = 0
                dicti[i] = a
                
    else:
        for k in range(a.shape[0]):
            a["MM"].iloc[k] = 0
        dicti[i] = a
        

#print(dicti["bird"].head())


/var/folders/l4/460145hx6fs0f8j2wwhgx5nc0000gn/T/ipykernel_13292/2882262259.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["MM"].iloc[k] = cosine
/var/folders/l4/460145hx6fs0f8j2wwhgx5nc0000gn/T/ipykernel_13292/2882262259.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["MM"].iloc[k] = 0
/var/folders/l4/460145hx6fs0f8j2wwhgx5nc0000gn/T/ipykernel_13292/2882262259.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a["MM"]

In [60]:
#driver code evaluation
total_correct = 0
total_wrong = 0
total_instances_counted = 0
for i in dicti.keys():
   
    
    if dicti[i].shape[0] > 1:
        
        correct,wrong,some = evaluation_algorithm(dicti[i],dicti[i],"SimLex999","MM")
        total_correct += correct
        total_wrong += wrong
        total_instances_counted+=1


        
    
print(total_correct)
print(total_wrong)


372
142


In [54]:
for i in dicti.keys():
    #print(dicti[i].shape)
    print(dicti[i].head())
    break

   word1  word2 POS SimLex999 conc(w1) conc(w2)        MM Assoc(USF)  \
0    old    new   A      1.58     2.72     2.81  0.496865       7.25   
29   old  fresh   A      0.87     2.72     1.97  0.340018       0.91   

   SimAssoc333 SD(SimLex)  
0            1       0.41  
29           1       1.64  


In [17]:
from sklearn.preprocessing import MinMaxScaler

# Assuming you have a term-term matrix named 'matrix' with shape (num_vectors, num_words)
# where each row represents a vector and each column represents a word

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Apply min-max scaling to each vector in the matrix
scaled_meaning_map = scaler.fit_transform(meaning_map.copy())

# 'scaled_matrix' now contains the scaled version of the term-term matrix,
# where each vector is scaled individually to the range [0, 1]